export const LOAD_USER = 'LOAD_USER';
export const UPDATE_ACCESS_TOKEN = 'UPDATE_ACCESS_TOKEN';
export const UPDATE_REFRESH_TOKEN = 'UPDATE_REFRESH_TOKEN';
export const SIGN_OUT = 'SIGN_OUT';
export const CREATE_AUTH_ERROR = 'CREATE_AUTH_ERROR';
export const CLEAN_AUTH_ERROR = 'CLEAN_AUTH_ERROR';